### PR TITLE
Fix GitHub action.yaml

### PR DESCRIPTION
**Pull request by hoopty**
Fix for #5 to change the `args` to be an array (of strings)

### CODE REVIEW

**Comment by krancour** [comment]
First of all, thank you @hoopty !

This was briefly discussed at the time the breakage occurred (see https://github.com/akuity/kargo-render-action/pull/4).

Obviously, we do want to fix this, but does anyone happen to have a reference as to _why_ this change is necessary?

If GitHub Actions has had a breaking change of this magnitude, I'm a bit surprised by that and would like some context.

cc @blakepettersson

**Comment by blakepettersson** [comment]
I haven't been able to find anything indicating `args` was anything other than an array on the internetz. I also tried to do a blame on Github's [docs repo](https://github.com/github/docs/blob/b49c7687772325b0e305a6037671172ecc7bfe0f/content/actions/creating-actions/creating-a-docker-container-action.md#creating-an-action-metadata-file) with the same results.

At this point I'd be inclined to contact Github Support to get their 2 cents...

**Comment by krancour** [comment]
@blakepettersson another question this raises...

Why do previous versions still work?

I will do some digging on Monday to try and get to the bottom of this.

**Comment by hoopty** [comment]
> First of all, thank you @hoopty !

Certainly, glad to help (even though in a very minor way).

> 
> This was briefly discussed at the time the breakage occurred (see #4).

I think something was missed, as the PR for #4 says: "We also set args as an array, since it seems like GH Actions has changed something on that front." but the PR change still kept is as a string, which would not work.

> 
> Obviously, we do want to fix this, but does anyone happen to have a reference as to _why_ this change is necessary?

This change is needed because the `args` requires an array of strings, and it is currently incorrectly specified as a standalone string.  Documentation: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsargs

> If GitHub Actions has had a breaking change of this magnitude, I'm a bit surprised by that and would like some context.

GH didn't change anything.  It looks like it was previously fixed here: https://github.com/akuity/kargo-render-action/commit/4305f8a024efe4c6daba8f656ba8760645a3c55d
What isn't clear to me is why it was reverted back to just a string here: https://github.com/akuity/kargo-render-action/commit/d1f44ee7da6a200ee274081e2d37576027490974

I suspect what may be misleading, or adding to the confusion is that is that the use of `args` is relatively new, prior to v0.1.0-rc.36, `entrypoint` was used instead and it was just a string.  That change is here: https://github.com/akuity/kargo-render-action/commit/a34f4bfed123b0b763c45a3b54cc26e58f185d4c

The short story is we have to change it to be an array of strings if we want it to work.

**Comment by krancour** [comment]
> I think something was missed, as the PR for https://github.com/akuity/kargo-render-action/pull/4 says: "We also set args as an array, since it seems like GH Actions has changed something on that front." but the PR change still kept is as a string, which would not work.

> GH didn't change anything. It looks like it was previously fixed here: https://github.com/akuity/kargo-render-action/commit/4305f8a024efe4c6daba8f656ba8760645a3c55d
What isn't clear to me is why it was reverted back to just a string here: https://github.com/akuity/kargo-render-action/commit/d1f44ee7da6a200ee274081e2d37576027490974

That particular piece of the PR was undone due to the same uncertainty we are discussing now. i.e. Lack of clarity on why the change was necessary, especially if GH hasn't changed anything.

> The short story is we have to change it to be an array of strings if we want it to work.

We'll get there. And we'll get there today.

**Comment by krancour** [comment]
Ok. I understand what happened now. This incorrect usage of `args` snuck in at the same time the CLI was refactored in v0.1.0-rc.36. Internally, we were using v0.1.0-rc.35 still, as most of the improvements from v0.1.0-rc.36 and up were more a benefit to Kargo proper than to the action. This is how incorrect usage of `args` went undetected.

So, as to the question of, "What changed on GitHub's end?" Nothing, actually.

As to the question of, "How was this working before?" From v0.1.0-rc.36 - v0.1.0-rc.39, it wasn't.

This LGTM and we will release a v0.1.0-rc.40.

**Review by krancour — APPROVED** [review]

**Pull request merged**
